[package]
name = "pretty"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dirs = "6.0.0"
mini-redis = "0.4.1"
open = "5.3.2"
reqwest = "0.12.12"
tokio = "1.43.0"
